version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/G-Research/geras
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - run:
          name: Build using go modules 
          command: go build ./...
      - run:
          name: Build using vendor directory
          command: go build -mod=vendor ./... 
      - run:
          name: Run unit tests 
          command: go test ./pkg/... 
