version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/G-Research/geras
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-cache
      - run:
          name: Build using vendor directory
          command: go build -mod=vendor ./cmd/geras
      - run:
          name: Build using go modules 
          command: go build ./...
      - run:
          name: Run unit tests 
          command: go test ./pkg/... 
      - run:
          name: Check flags are documented
          command: test/flags-doc.sh

      # Create a docker environment we can use to build docker images
      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          docker_layer_caching: true
      # Go base image doesn't have docker CLI, so need to install it
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker build
          command: docker build -t g-research/geras:$CIRCLE_BRANCH .

      - save_cache: 
          key: pkg-cache
          paths:
            - "/go/pkg"
