version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/G-Research/geras
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
      SOURCE_IMAGE: g-research/geras
      IMAGE_NAME: docker.pkg.github.com/g-research/geras/autobuild
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-cache
      - run:
          name: Build geras binary
          command: go build ./cmd/geras
      - run:
          name: Run unit tests 
          command: go test ./...
      - run:
          name: Check flags are documented
          command: test/flags-doc.sh

      # Create a docker environment we can use to build docker images
      # See https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Docker build
          command: |
            extra=
            if [[ "$CIRCLE_TAG" != "" ]]; then
              extra="--build-arg GERAS_VERSION=$CIRCLE_TAG"
            fi
            docker build -t g-research/geras:$CIRCLE_BRANCH --build-arg GIT_REVISION="$CIRCLE_SHA1" --build-arg GIT_BRANCH="$CIRCLE_BRANCH" --build-arg BUILD_USER="circleci" $extra .

      - run:
          name: Docker run without flags
          command: |
            set +e
            docker run -t g-research/geras:$CIRCLE_BRANCH
            exit=$?
            # No flags; so expect help output. Also puts the version output into the CircleCI log
            if [[ $exit != 1 ]]; then
              echo "Unexpected exit code: $exit"
              exit 1
            fi
            exit 0

      - run:
          name: Push autobuild Docker image
          command: |
            if [[ $CIRCLE_TAG == "" ]] || [[ $CIRCLE_BRANCH != "docker-tag-release" ]]; then
              echo "Not on a tag or master, skipped."
              exit 0
            fi
            tag="$CIRCLE_TAG"
            if [[ $tag == "" ]]; then
              tag="$CIRCLE_BRANCH"
            fi
            echo "$GITHUB_DOCKER_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_DOCKER_USER" --password-stdin
            docker tag $SOURCE_IMAGE:$CIRCLE_BRANCH $IMAGE_NAME:$tag
            docker push $IMAGE_NAME:$tag

      - save_cache: 
          key: pkg-cache
          paths:
            - "/go/pkg"

  docker_release:
    docker:
      - image: circleci/golang:1.12.5
    environment:
      SOURCE_IMAGE: docker.pkg.github.com/g-research/geras/autobuild
      IMAGE_NAME: docker.pkg.github.com/g-research/geras/release
    steps:
      - setup_remote_docker
      - run:
          name: Release tagged commit as release Docker image
          command: |
            echo "$GITHUB_DOCKER_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_DOCKER_USER" --password-stdin
            docker pull $SOURCE_IMAGE:$CIRCLE_TAG
            docker pull $IMAGE_NAME:$CIRCLE_TAG
            existing=$(docker images -q $IMAGE_NAME:$CIRCLE_TAG)
            if [[ $existing != "" ]]; then
              echo "Tag already exists, not overwriting"
              exit 1
            fi
            docker tag $SOURCE_IMAGE:$CIRCLE_BRANCH $IMAGE_NAME:$CIRCLE_TAG
            docker push $IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - docker_push:
          requires:
            - build
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
