version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/G-Research/geras
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - run:
          name: Run unit tests 
          command: go test ./pkg/... 
