version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/G-Research/geras
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-cache
      - run:
          name: Build using vendor directory
          command: go build -mod=vendor ./cmd/geras
      - run:
          name: Build using go modules 
          command: go build ./...
      - run:
          name: Run unit tests 
          command: go test ./pkg/... 
      - run:
          name: Check flags are documented
          command: test/flags-doc.sh
      - run:
          name: Docker build
          command: docker build -t G-Research/geras:$CIRCLE_BRANCH .
      - save_cache: 
          key: pkg-cache
          paths:
            - "/go/pkg"
