name: Need Help?
description: Ask a question or request help regarding Geras
title: "[QUESTION]: <title>"
labels: [ "question" ]

body:
  - type: textarea
    id: question-details
    attributes:
      label: Question / Problem
      description: Provide a clear and concise description of your question or the issue you're facing.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Please provide details about your environment:"
      value: |
        - Geras Version: [e.g., 1.3.0]
        - Thanos Version: [e.g., 0.32.5]
        - OpenTSDB Version: [e.g., 2.4.1]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include any relevant context, screenshots, or code snippets that can help us better understand and address your question or problem.
    validations:
      required: false
