name: Bug report
description: Create a report to help us improve Geras
title: "[BUG]: <title>"
labels: [ "bug" ]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting this issue!**        
        To help us understand and address the problem effectively, please provide detailed information. 
        You can refer to [this guide](https://stackoverflow.com/help/mcve) for tips on creating a good bug report.

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Please provide details about your environment:"
      value: |
        - Geras Version: [e.g., 1.3.0]
        - Thanos Version: [e.g., 0.32.5]
        - OpenTSDB Version: [e.g., 2.4.1]
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: "Detailed steps to reproduce the behavior:"
      placeholder: |
        1. Provide a detailed description of the steps taken.
        2. Specify any relevant configuration or input data.
        3. Explain the observed behavior or error message.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context about the problem here, including log outputs or screenshots if applicable.
    validations:
      required: false
